- hosts: all
  gather_facts: false
   # *Become* root
  become: true
   # Speeds up the script
  gather_facts: false

  tasks:
     # Include the Docker installation Ansible play file (empty for now)
     - include: install_docker.yml

     - name: check swarm is active
       shell: 'docker info | grep "Swarm: active"'
       register: swarm_active
       ignore_errors: true

     - name: swarm init
       when: swarm_active.rc == 1
       shell: docker swarm init  --advertise-addr 12.0.0.2:2377

     - name: get swarm token
       shell: docker swarm join-token -q worker > /vagrant/worker_token

     - name: create file daemon.json
       copy:
         dest: "/etc/docker/daemon.json"
         content: |
             {
                "metrics-addr" : "0.0.0.0:9323",
                "experimental" : true
              }

     - name: Print some dummy thing
       shell: echo "It works!"
