version: '3'


networks:
  net-monitoring:

services:
  cadvisor:
    image: google/cadvisor:v0.29.0
    links:
      - influxdb:influxsrv
    command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxsrv:8086
    restart: always
    ports:
      - "8082:8080"
    networks:
      - net-monitoring
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  prom:
    image: quay.io/prometheus/prometheus:v2.0.0
    volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
     - "9090:9090"
    networks:
      - net-monitoring

  grafana:
    image: grafana/grafana
    user: "1000"
    volumes:
      - ../grafana/grafana.ini:/etc/grafana/grafana.ini
      - ../grafana/grafana-storage:/var/lib/grafana
    ports:
      - "3002:3000"
    networks:
      - net-monitoring
